import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { ApolloProvider } from '@autospace/network/src/config/apollo'
import '@autospace/ui/app/globals.css'
import { SessionProvider } from '@autospace/ui/components/molecules/SessionProvider'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <ApolloProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            {children}
          </body>
        </ApolloProvider>
      </SessionProvider>
    </html>
  )
}
